#!/bin/bash
#
# Mamori LLC copyright 2026.
#
# Discover, verify, install, or upgrade HAProxy on the Mamori HA gateway host.
#
# Flow:
#   sudo ./install-ha-haproxy.sh --verify
#   sudo ./install-ha-haproxy.sh --install --seed-name m1 --seed-ip 10.240.0.11
#   sudo ./install-ha-haproxy.sh --upgrade
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/gateway-service-common.sh
source "${SCRIPT_DIR}/lib/gateway-service-common.sh"

HAPROXY_CFG="${HAPROXY_CFG:-/etc/haproxy/haproxy.cfg}"
BACKUP_DIR="${BACKUP_DIR:-/opt/mamori/lb-backup}"
TEMPLATE="${SCRIPT_DIR}/templates/haproxy.cfg"
PROFILE_PATH="${HAPROXY_PROFILE:-${SCRIPT_DIR}/gateway-haproxy.env}"

MODE=""
FORCE=0
SEED_NAME=""
SEED_IP=""
SEED_ID=""
VERIFY_ERRORS=0

usage() {
  cat <<EOF
Usage: $0 --verify|--install|--upgrade [options]

Install Ubuntu HAProxy with a Mamori listen-block template suitable for
manage-lb-node.sh (seed server lines required).

  --verify    Discover package/config, write profile
  --install   apt install + template (requires --seed-name and --seed-ip)
  --upgrade   apt --only-upgrade + configtest + reload (needs --verify profile)

Options:
  --config PATH         Profile path (default: ${SCRIPT_DIR}/gateway-haproxy.env)
  --seed-name NAME      First app node hostname (e.g. m1) [--install]
  --seed-ip IP          First app node IP reachable from gateway [--install]
  --seed-id ID          HAProxy server id (default: mamorihubN from mN)
  --haproxy PATH        Config path (default: /etc/haproxy/haproxy.cfg)
  --force               Overwrite existing haproxy.cfg with template (backs up first)
  -h, --help

After install, register more nodes with:
  bash manage-lb-node.sh --register --name m2 --ip <ip>
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --verify) MODE=verify ;;
    --install) MODE=install ;;
    --upgrade) MODE=upgrade ;;
    --config)
      shift
      PROFILE_PATH="${1:-}"
      ;;
    --seed-name)
      shift
      SEED_NAME="${1:-}"
      ;;
    --seed-ip)
      shift
      SEED_IP="${1:-}"
      ;;
    --seed-id)
      shift
      SEED_ID="${1:-}"
      ;;
    --haproxy)
      shift
      HAPROXY_CFG="${1:-}"
      ;;
    --force) FORCE=1 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

[ -n "$MODE" ] || { echo "ERROR: specify --verify, --install, or --upgrade" >&2; usage >&2; exit 1; }

require_root

derive_seed_id() {
  if [ -n "$SEED_ID" ]; then
    return 0
  fi
  if [[ "$SEED_NAME" =~ ^m([0-9]+)$ ]]; then
    SEED_ID="mamorihub${BASH_REMATCH[1]}"
  else
    SEED_ID="mamorihub1"
  fi
}

render_template() {
  derive_seed_id
  local tmp
  tmp=$(mktemp)
  sed -e "s/__SEED_ID__/${SEED_ID}/g" -e "s/__SEED_IP__/${SEED_IP}/g" "$TEMPLATE" > "$tmp"
  echo "$tmp"
}

count_listen_blocks() {
  local f="$1"
  [ -f "$f" ] || { echo 0; return; }
  grep -cE '^[[:space:]]*listen[[:space:]]+' "$f" 2>/dev/null || echo 0
}

haproxy_version() {
  if command_exists haproxy; then
    extract_version "$(haproxy -v 2>&1 | head -1)"
  fi
}

discover_and_verify() {
  echo "=== HAProxy verify ==="
  VERIFY_ERRORS=0
  local ver="" listens=0 active="false"

  if command_exists haproxy; then
    ver=$(haproxy_version)
    ok "haproxy installed (version ${ver:-unknown})"
  else
    warn "haproxy not installed (ok before --install)"
  fi

  if [ -f "$HAPROXY_CFG" ]; then
    ok "config present: ${HAPROXY_CFG}"
    listens=$(count_listen_blocks "$HAPROXY_CFG")
    ok "listen blocks: ${listens}"
    if command_exists haproxy; then
      if haproxy -c -f "$HAPROXY_CFG" >/dev/null 2>&1; then
        ok "haproxy -c passed"
      else
        fail "haproxy -c failed for ${HAPROXY_CFG}"
      fi
    fi
  else
    warn "config missing: ${HAPROXY_CFG}"
  fi

  if systemd_active haproxy; then
    active=true
    ok "haproxy service active"
  else
    warn "haproxy service not active"
  fi

  if [ "$VERIFY_ERRORS" -gt 0 ]; then
    echo "Verify FAILED with ${VERIFY_ERRORS} error(s). Profile NOT written." >&2
    exit 1
  fi

  write_profile_file "$PROFILE_PATH" <<EOF
# Generated by install-ha-haproxy.sh --verify
PROFILE_VERSION=1
DISCOVERED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
HOSTNAME=$(hostname -f 2>/dev/null || hostname)
HAPROXY_CFG=${HAPROXY_CFG}
HAPROXY_VERSION=${ver}
HAPROXY_LISTEN_COUNT=${listens}
HAPROXY_ACTIVE=${active}
EOF
  echo "Verify PASSED."
}

do_install() {
  echo "=== HAProxy install ==="
  if [ -z "$SEED_NAME" ] || [ -z "$SEED_IP" ]; then
    echo "ERROR: --install requires --seed-name and --seed-ip" >&2
    exit 1
  fi
  [ -f "$TEMPLATE" ] || { echo "ERROR: template missing: ${TEMPLATE}" >&2; exit 1; }

  if ! command_exists haproxy; then
    apt_install_pkg haproxy
  else
    ok "haproxy already installed"
  fi

  if [ -f "$HAPROXY_CFG" ] && [ "$FORCE" -ne 1 ]; then
    echo "ERROR: ${HAPROXY_CFG} exists (use --force to replace; backs up first)" >&2
    exit 1
  fi

  if [ -f "$HAPROXY_CFG" ]; then
    local bak
    bak=$(backup_file "$HAPROXY_CFG" "$BACKUP_DIR")
    ok "backed up to ${bak}"
  fi

  local rendered
  rendered=$(render_template)
  mkdir -p "$(dirname "$HAPROXY_CFG")"
  mv "$rendered" "$HAPROXY_CFG"
  chmod 644 "$HAPROXY_CFG"
  ok "wrote ${HAPROXY_CFG} (seed ${SEED_ID:-} ${SEED_NAME} ${SEED_IP})"

  if ! haproxy -c -f "$HAPROXY_CFG"; then
    echo "ERROR: haproxy -c failed" >&2
    exit 1
  fi

  systemctl enable haproxy
  systemctl restart haproxy
  ok "haproxy enabled and restarted"
  echo "Done. Register additional nodes with manage-lb-node.sh"
}

do_upgrade() {
  echo "=== HAProxy upgrade ==="
  load_profile_file "$PROFILE_PATH"
  HAPROXY_CFG="${HAPROXY_CFG:-/etc/haproxy/haproxy.cfg}"

  apt_upgrade_pkg haproxy
  if [ -f "$HAPROXY_CFG" ]; then
    haproxy -c -f "$HAPROXY_CFG"
  fi
  systemctl reload haproxy || systemctl restart haproxy
  ok "haproxy upgraded and reloaded (config not overwritten)"
}

case "$MODE" in
  verify) discover_and_verify ;;
  install) do_install ;;
  upgrade) do_upgrade ;;
esac
