#!/bin/bash
#
# Mamori LLC copyright 2026.
#
# Back up an all-in-one Mamori Docker deployment (named volumes + helper image)
# for migration to a new host. Writes a companion restore.sh into the backup
# directory.
#
# Usage:
#   bash backup-aio.sh
#   bash backup-aio.sh --output /path/to/mamori-backups
#   DOCKER=docker bash backup-aio.sh
#   bash backup-aio.sh --no-stop   # do not stop the mamori container first
#
set -euo pipefail

DOCKER="${DOCKER:-sudo docker}"
CONTAINER_NAME="${CONTAINER_NAME:-mamori}"
HELPER_IMAGE="${HELPER_IMAGE:-mamori-alpine-boringtun}"
OUTPUT_DIR=""
STOP_CONTAINER=1

usage() {
    cat <<'EOF'
Usage: backup-aio.sh [options]

Back up Mamori named Docker volumes and the mamori-alpine-boringtun helper
image into an output directory, and write restore.sh for the target host.

Options:
  -o, --output <dir>   Backup directory (default: ./mamori-backups)
      --no-stop        Do not stop the mamori container before backup
  -h, --help           Show this help

Environment:
  DOCKER           Docker CLI (default: sudo docker)
  CONTAINER_NAME   Container to inspect (default: mamori)
  HELPER_IMAGE     Image used to pack/unpack volumes (default: mamori-alpine-boringtun)

Typical migration:
  1. On the source host:  bash backup-aio.sh
  2. Copy the output directory to the target (Docker installed; Mamori not yet)
  3. On the target:       bash restore.sh   (from inside the backup directory)
  4. Install Mamori on the target (media/install-*.sh)

EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -o|--output)
            OUTPUT_DIR="${2:-}"
            [[ -n "$OUTPUT_DIR" ]] || { echo "Missing value for --output" >&2; exit 1; }
            shift 2
            ;;
        --no-stop)
            STOP_CONTAINER=0
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [[ -z "$OUTPUT_DIR" ]]; then
    OUTPUT_DIR="$(pwd)/mamori-backups"
fi
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

if ! $DOCKER inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
    echo "ERROR: container '$CONTAINER_NAME' not found" >&2
    exit 1
fi

if ! $DOCKER image inspect "$HELPER_IMAGE" >/dev/null 2>&1; then
    echo "ERROR: helper image '$HELPER_IMAGE' not found locally" >&2
    exit 1
fi

echo "Mamori AIO backup"
echo "  DOCKER=$DOCKER"
echo "  container=$CONTAINER_NAME"
echo "  helper=$HELPER_IMAGE"
echo "  output=$OUTPUT_DIR"
echo ""

WAS_RUNNING=0
if [[ "$STOP_CONTAINER" -eq 1 ]]; then
    if $DOCKER inspect -f '{{.State.Running}}' "$CONTAINER_NAME" 2>/dev/null | grep -qi true; then
        WAS_RUNNING=1
        echo "Stopping $CONTAINER_NAME ..."
        $DOCKER stop "$CONTAINER_NAME"
    fi
fi

# Collect named volumes whose names start with "mamori"
mapfile -t VOLUME_LINES < <(
    $DOCKER container inspect -f '{{ range .Mounts }}{{.Type}} {{ .Name }} {{ .Destination }}{{println}}{{ end }}' "$CONTAINER_NAME" \
        | grep "^volume mamori" || true
)

if [[ ${#VOLUME_LINES[@]} -eq 0 ]]; then
    echo "ERROR: no named volumes matching 'mamori*' on container '$CONTAINER_NAME'" >&2
    exit 1
fi

MANIFEST="$OUTPUT_DIR/volumes.tsv"
: > "$MANIFEST"

echo "Archiving volumes ..."
for line in "${VOLUME_LINES[@]}"; do
    # Type Name Destination
    vol_name="$(awk '{print $2}' <<<"$line")"
    vol_dest="$(awk '{print $3}' <<<"$line")"
    echo "  $vol_name -> $vol_dest"
    echo -e "${vol_name}\t${vol_dest}" >> "$MANIFEST"
    $DOCKER run --rm \
        --volumes-from "$CONTAINER_NAME" \
        --volume "$OUTPUT_DIR:/backups" \
        "$HELPER_IMAGE" \
        sh -c "cd ${vol_dest} && tar zcvf /backups/${vol_name}.tgz ."
done

echo "Saving helper image $HELPER_IMAGE ..."
$DOCKER image save "$HELPER_IMAGE" | gzip > "$OUTPUT_DIR/${HELPER_IMAGE}.tgz"

RESTORE_SH="$OUTPUT_DIR/restore.sh"
cat > "$RESTORE_SH" <<EOF
#!/bin/sh
#
# Generated by backup-aio.sh — restore Mamori volumes on a target host.
# Run from this directory after Docker is installed and before Mamori install.
#
set -eu
DOCKER="\${DOCKER:-sudo docker}"
HELPER_IMAGE="${HELPER_IMAGE}"
HERE="\$(CDPATH= cd -- "\$(dirname "\$0")" && pwd)"
cd "\$HERE"

echo "Loading helper image ..."
\$DOCKER load < "\${HELPER_IMAGE}.tgz"

EOF

while IFS=$'\t' read -r vol_name vol_dest; do
    [[ -z "$vol_name" ]] && continue
    cat >> "$RESTORE_SH" <<EOF
echo "Restoring volume ${vol_name} -> ${vol_dest} ..."
\$DOCKER run --rm -i \\
    --volume ${vol_name}:${vol_dest} \\
    --volume "\$HERE:/backups" \\
    "\$HELPER_IMAGE" \\
    sh -c "cd ${vol_dest} && tar zxvf /backups/${vol_name}.tgz"

EOF
done < "$MANIFEST"

cat >> "$RESTORE_SH" <<'EOF'
echo "Restore complete."
echo "Next: install Mamori on this host (media/install-*.sh)."
EOF

chmod +x "$RESTORE_SH"

# Also copy the repo restore helper if present next to this script (optional convenience)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/restore-aio.sh" ]]; then
    cp -f "$SCRIPT_DIR/restore-aio.sh" "$OUTPUT_DIR/restore-aio.sh"
fi

if [[ "$WAS_RUNNING" -eq 1 ]]; then
    echo "Starting $CONTAINER_NAME ..."
    $DOCKER start "$CONTAINER_NAME"
fi

echo ""
echo "Backup complete: $OUTPUT_DIR"
echo "  volumes.tsv  — volume name / mount map"
echo "  *.tgz        — volume archives and helper image"
echo "  restore.sh   — run on the target host before Mamori install"
