# Shared Mamori host-firewall profile helpers.
# Safe to source. Used by firewall/setup-firewall.sh and validate-firewall.sh.
#
# Profile env (repo-root .mamori-firewall.env):
#   MAMORI_FW_WIREGUARD=0|1
#   MAMORI_FW_WG_CIDR=172.0.0.0/16
#   MAMORI_FW_DB_PROXIES=0|1   # open DB/SSH proxy ports to any source
#   MAMORI_FW_RDP=0|1          # open guacd 4822 to any source
#   MAMORI_FW_WEB_PROXY=0|1    # open HTTP/S proxy 8089 to any source
#   MAMORI_FW_INTERNET_EXPOSED=0|1
#   MAMORI_FW_DB_PUBLIC=0|1    # confirmed public DB exposure
#   MAMORI_FW_RDP_PUBLIC=0|1   # confirmed public RDP exposure
#   MAMORI_FW_WEB_PUBLIC=0|1   # confirmed public WEB proxy exposure
#   MAMORI_FW_BACKEND=ufw|firewalld

_FW_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_FW_REPO_ROOT="$(cd "$_FW_LIB_DIR/.." && pwd)"
MAMORI_FIREWALL_ENV_FILE="${MAMORI_FIREWALL_ENV_FILE:-$_FW_REPO_ROOT/.mamori-firewall.env}"

MAMORI_FW_WIREGUARD="${MAMORI_FW_WIREGUARD:-0}"
MAMORI_FW_WG_CIDR="${MAMORI_FW_WG_CIDR:-172.0.0.0/16}"
MAMORI_FW_DB_PROXIES="${MAMORI_FW_DB_PROXIES:-0}"
MAMORI_FW_INTERNET_EXPOSED="${MAMORI_FW_INTERNET_EXPOSED:-0}"
MAMORI_FW_DB_PUBLIC="${MAMORI_FW_DB_PUBLIC:-0}"
MAMORI_FW_RDP="${MAMORI_FW_RDP:-0}"
MAMORI_FW_RDP_PUBLIC="${MAMORI_FW_RDP_PUBLIC:-0}"
MAMORI_FW_WEB_PROXY="${MAMORI_FW_WEB_PROXY:-0}"
MAMORI_FW_WEB_PUBLIC="${MAMORI_FW_WEB_PUBLIC:-0}"
MAMORI_FW_BACKEND="${MAMORI_FW_BACKEND:-}"

# Always-open management ports (proto|port|comment)
mamori_fw_always_rules() {
    cat <<'EOF'
tcp|22|SSH
tcp|443|HTTPS portal
EOF
}

mamori_fw_db_proxy_rules() {
    cat <<'EOF'
tcp|1122|SSH proxy
tcp|5432|Postgres proxy
tcp|1433|MSSQL proxy
tcp|3306|MySQL proxy
tcp|1521|Oracle proxy
tcp|28017|Mongo proxy
tcp|1527|Mamori JDBC proxy
EOF
}

mamori_fw_rdp_rules() {
    cat <<'EOF'
tcp|4822|RDP guacd
EOF
}

mamori_fw_web_proxy_rules() {
    cat <<'EOF'
tcp|8089|HTTP/S proxy
EOF
}

mamori_fw_wireguard_port_rules() {
    cat <<'EOF'
udp|51871|WireGuard
EOF
}

# Print all port rules for the current profile (proto/port/comment), one per line.
mamori_fw_expected_port_rules() {
    mamori_fw_always_rules
    if [[ "${MAMORI_FW_DB_PROXIES}" == "1" ]]; then
        mamori_fw_db_proxy_rules
    fi
    if [[ "${MAMORI_FW_RDP}" == "1" ]]; then
        mamori_fw_rdp_rules
    fi
    if [[ "${MAMORI_FW_WEB_PROXY}" == "1" ]]; then
        mamori_fw_web_proxy_rules
    fi
    if [[ "${MAMORI_FW_WIREGUARD}" == "1" ]]; then
        mamori_fw_wireguard_port_rules
    fi
}

mamori_fw_detect_backend() {
    local id like
    # shellcheck disable=SC1091
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        id="${ID:-}"
        like="${ID_LIKE:-}"
    fi
    case "$id" in
        ubuntu|debian)
            printf '%s' ufw
            return 0
            ;;
        rhel|centos|rocky|almalinux|fedora|ol)
            printf '%s' firewalld
            return 0
            ;;
    esac
    case " $like " in
        *" debian "*|*" ubuntu "*)
            printf '%s' ufw
            return 0
            ;;
        *" rhel "*|*" fedora "*|*" centos "*)
            printf '%s' firewalld
            return 0
            ;;
    esac
    if command -v firewall-cmd >/dev/null 2>&1; then
        printf '%s' firewalld
        return 0
    fi
    if command -v ufw >/dev/null 2>&1; then
        printf '%s' ufw
        return 0
    fi
    return 1
}

mamori_fw_load_env() {
    if [[ -f "$MAMORI_FIREWALL_ENV_FILE" ]]; then
        # shellcheck disable=SC1090
        set -a
        # shellcheck source=/dev/null
        . "$MAMORI_FIREWALL_ENV_FILE"
        set +a
    fi
}

mamori_fw_save_env() {
    umask 077
    cat >"$MAMORI_FIREWALL_ENV_FILE" <<EOF
# Mamori host firewall profile (generated by setup-firewall.sh)
MAMORI_FW_BACKEND=${MAMORI_FW_BACKEND}
MAMORI_FW_WIREGUARD=${MAMORI_FW_WIREGUARD}
MAMORI_FW_WG_CIDR=${MAMORI_FW_WG_CIDR}
MAMORI_FW_DB_PROXIES=${MAMORI_FW_DB_PROXIES}
MAMORI_FW_INTERNET_EXPOSED=${MAMORI_FW_INTERNET_EXPOSED}
MAMORI_FW_DB_PUBLIC=${MAMORI_FW_DB_PUBLIC}
MAMORI_FW_RDP=${MAMORI_FW_RDP}
MAMORI_FW_RDP_PUBLIC=${MAMORI_FW_RDP_PUBLIC}
MAMORI_FW_WEB_PROXY=${MAMORI_FW_WEB_PROXY}
MAMORI_FW_WEB_PUBLIC=${MAMORI_FW_WEB_PUBLIC}
EOF
    chmod 600 "$MAMORI_FIREWALL_ENV_FILE" 2>/dev/null || true
    echo "Wrote $MAMORI_FIREWALL_ENV_FILE"
}

# Refuse opening optional service ports to any source on an internet-exposed
# host unless the matching *_PUBLIC flag is set. Returns 0 if OK, 1 if refuse.
mamori_fw_check_public_ports_policy() {
    local ok=0
    if [[ "${MAMORI_FW_INTERNET_EXPOSED}" != "1" ]]; then
        return 0
    fi
    if [[ "${MAMORI_FW_DB_PROXIES}" == "1" && "${MAMORI_FW_DB_PUBLIC}" != "1" ]]; then
        echo "ERROR: --db-proxies on an internet-exposed host opens DB/SSH proxy" >&2
        echo "       ports to any source. Prefer WireGuard. To open anyway, pass --db-public." >&2
        ok=1
    fi
    if [[ "${MAMORI_FW_RDP}" == "1" && "${MAMORI_FW_RDP_PUBLIC}" != "1" ]]; then
        echo "ERROR: --rdp on an internet-exposed host opens TCP 4822 to any source." >&2
        echo "       Prefer WireGuard. To open anyway, pass --rdp-public." >&2
        ok=1
    fi
    if [[ "${MAMORI_FW_WEB_PROXY}" == "1" && "${MAMORI_FW_WEB_PUBLIC}" != "1" ]]; then
        echo "ERROR: --web-proxy on an internet-exposed host opens TCP 8089 to any source." >&2
        echo "       Prefer WireGuard. To open anyway, pass --web-public." >&2
        ok=1
    fi
    if [[ "$ok" -ne 0 ]]; then
        echo "       WireGuard clients on the WG CIDR already reach these ports" >&2
        echo "       without per-port public rules." >&2
        return 1
    fi
    return 0
}

# Prompt for an optional any-source port group.
# $1 label  $2 varname for enable (e.g. MAMORI_FW_RDP)  $3 varname for public flag
mamori_fw_prompt_any_source_ports() {
    local label="$1"
    local enable_var="$2"
    local public_var="$3"
    local want

    printf -v "$enable_var" '%s' "0"
    printf -v "$public_var" '%s' "0"

    if [[ "${MAMORI_FW_INTERNET_EXPOSED}" == "1" ]]; then
        echo ""
        echo "WARNING: Opening ${label} on an internet-facing host exposes it to"
        echo "         any source. Prefer WireGuard (or a private network)."
        if [[ "$MAMORI_FW_WIREGUARD" == "1" ]]; then
            echo "         WireGuard clients on ${MAMORI_FW_WG_CIDR} already reach"
            echo "         these ports via the client-network allow."
        fi
        mamori_fw_yn "Open ${label} to any source anyway?" N
        want="$REPLY"
        if [[ "$want" == "1" ]]; then
            printf -v "$enable_var" '%s' "1"
            printf -v "$public_var" '%s' "1"
        else
            echo "Skipping public ${label} rules."
        fi
    else
        mamori_fw_yn "Open ${label} to any source?" N
        want="$REPLY"
        if [[ "$want" == "1" ]]; then
            printf -v "$enable_var" '%s' "1"
        fi
    fi
}

mamori_fw_yn() {
    # $1 prompt  $2 default Y|N  -> sets REPLY to 0|1
    local prompt="$1"
    local def="${2:-N}"
    local answer
    if [[ ! -t 0 ]]; then
        case "$def" in
            y|Y) REPLY=1 ;;
            *) REPLY=0 ;;
        esac
        return 0
    fi
    if [[ "$def" == "Y" || "$def" == "y" ]]; then
        read -r -p "$prompt [Y/n] " answer
        answer="${answer:-Y}"
    else
        read -r -p "$prompt [y/N] " answer
        answer="${answer:-N}"
    fi
    case "$answer" in
        y|Y|yes|YES) REPLY=1 ;;
        *) REPLY=0 ;;
    esac
}

mamori_fw_prompt_profile() {
    local answer
    echo ""
    echo "Configure which Mamori features are exposed on the host firewall."
    echo "Always opened: TCP 22 (SSH), TCP 443 (HTTPS)."
    echo ""

    mamori_fw_yn "Enable WireGuard (UDP 51871 + client network)?" N
    MAMORI_FW_WIREGUARD="$REPLY"
    if [[ "$MAMORI_FW_WIREGUARD" == "1" ]]; then
        if [[ -t 0 ]]; then
            read -r -p "WireGuard network CIDR [${MAMORI_FW_WG_CIDR}]: " answer
            MAMORI_FW_WG_CIDR="${answer:-$MAMORI_FW_WG_CIDR}"
        fi
        echo ""
        echo "Note: WireGuard clients on ${MAMORI_FW_WG_CIDR} are allowed to all"
        echo "      host ports (DB proxies, RDP/guacd 4822, WEB proxy 8089, …)."
        echo "      You do not need to open those ports publicly for WireGuard users."
        echo ""
    fi

    mamori_fw_yn "Is this Mamori server exposed to the internet (public IP / NAT)?" N
    MAMORI_FW_INTERNET_EXPOSED="$REPLY"

    MAMORI_FW_DB_PROXIES=0
    MAMORI_FW_DB_PUBLIC=0
    MAMORI_FW_RDP=0
    MAMORI_FW_RDP_PUBLIC=0
    MAMORI_FW_WEB_PROXY=0
    MAMORI_FW_WEB_PUBLIC=0

    mamori_fw_prompt_any_source_ports \
        "DB proxy ports (SSH/Postgres/MSSQL/MySQL/Oracle/Mongo/JDBC)" \
        MAMORI_FW_DB_PROXIES MAMORI_FW_DB_PUBLIC

    mamori_fw_prompt_any_source_ports \
        "RDP (guacd TCP 4822)" \
        MAMORI_FW_RDP MAMORI_FW_RDP_PUBLIC

    mamori_fw_prompt_any_source_ports \
        "WEB HTTP/S proxy (TCP 8089)" \
        MAMORI_FW_WEB_PROXY MAMORI_FW_WEB_PUBLIC
}

mamori_fw_print_profile() {
    echo "Firewall profile:"
    echo "  backend:           ${MAMORI_FW_BACKEND}"
    echo "  wireguard:         ${MAMORI_FW_WIREGUARD}  cidr=${MAMORI_FW_WG_CIDR}"
    echo "  internet_exposed:  ${MAMORI_FW_INTERNET_EXPOSED}"
    echo "  db_proxies:        ${MAMORI_FW_DB_PROXIES}  (public=${MAMORI_FW_DB_PUBLIC})"
    echo "  rdp:               ${MAMORI_FW_RDP}  (public=${MAMORI_FW_RDP_PUBLIC})"
    echo "  web_proxy:         ${MAMORI_FW_WEB_PROXY}  (public=${MAMORI_FW_WEB_PUBLIC})"
    echo "  ports:"
    while IFS='|' read -r proto port comment; do
        echo "    ${proto^^}/$port  $comment"
    done < <(mamori_fw_expected_port_rules)
    if [[ "${MAMORI_FW_WIREGUARD}" == "1" ]]; then
        echo "    allow from ${MAMORI_FW_WG_CIDR} (WireGuard clients — all ports)"
    fi
}

mamori_fw_ensure_package() {
    local backend="$1"
    if [[ "$backend" == "ufw" ]]; then
        if command -v ufw >/dev/null 2>&1; then
            return 0
        fi
        echo "ufw is not installed."
        if [[ -t 0 ]]; then
            local answer
            read -r -p "Install ufw now? [Y/n] " answer
            answer="${answer:-Y}"
            case "$answer" in
                y|Y|yes|YES)
                    sudo apt-get update && sudo apt-get install -y ufw
                    return $?
                    ;;
            esac
        fi
        echo "ERROR: install ufw (apt install ufw) and re-run." >&2
        return 1
    fi

    if [[ "$backend" == "firewalld" ]]; then
        if command -v firewall-cmd >/dev/null 2>&1; then
            return 0
        fi
        echo "firewalld is not installed."
        if [[ -t 0 ]]; then
            local answer
            read -r -p "Install firewalld now? [Y/n] " answer
            answer="${answer:-Y}"
            case "$answer" in
                y|Y|yes|YES)
                    if command -v dnf >/dev/null 2>&1; then
                        sudo dnf install -y firewalld
                    else
                        sudo yum install -y firewalld
                    fi
                    sudo systemctl enable --now firewalld
                    return $?
                    ;;
            esac
        fi
        echo "ERROR: install firewalld and re-run." >&2
        return 1
    fi
    echo "ERROR: unknown firewall backend '$backend'" >&2
    return 1
}
